name: ThinkG
favicon: null
layout_spectrum: 0.25899
typography_spectrum: 0.7694
title: ThinkG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141d24'
    - '#96a1a5'
    - '#666761'
    - '#e1b829'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
