name: ThinkG
favicon: null
layout_spectrum: 0.66668
typography_spectrum: 0.85127
title: ThinkG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#223e63'
    - '#7599b7'
    - '#bdbeba'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
