name: ThinkG
favicon: null
layout_spectrum: 0.97103
typography_spectrum: 0.85127
title: ThinkG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1109'
    - '#fdfdfd'
    - '#74643d'
    - '#4e2b15'
    - '#d0aa70'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
