name: ThinkG
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74935
title: ThinkG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141d24'
    - '#96a1a5'
    - '#666761'
    - '#e1b829'
  brandStrength: 0.4375
  lightness: 0.5303710135631263
  saturation: 0.5625
  rhythmicContrast: 0.4763746904209256
purpose: []
